components/speakers/SpeakerIcon.tsx, components/speakers/SpeakerIconList.tsx
It would always redirect to twitter.com/undefined. Removed Twitter boolean to just checking if the speaker.twitter exists
=> Fixed bug where the Twitter handle would be undefined

app/[organization]/[event]/layout.tsx, components/Layout/Navbar.tsx
I also changed "Home" to "Schedule". It was a bit misleading
=> Changed Navbar to have less space between the icons.

app/(home)/components/EventList.tsx, app/(home)/components/FilterBar.tsx, app/[organization]/[event]/archive/components/FilteredItems.tsx, app/[organization]/[event]/archive/page.tsx, app/[organization]/[event]/session/[session]/components/SessionComponent.tsx, components/misc/ComponentCard.tsx, components/misc/Player.tsx, components/sessions/SessionInfoBox.tsx, tailwind.config.js
I changed the following:
- Date is now placed next to the title
- SpeakerCard is now "sticky"
- Description is wrapped with "justify" and the icons are under the description
- Added an aspect ratio to the <Player> tag
Checked on Large and small screens
=> Changed the UX of the SessionCard

app/(home)/components/FilterBar.tsx, app/[organization]/[event]/archive/components/ArchivedSession.tsx, app/[organization]/[event]/archive/components/FilteredItems.tsx, app/[organization]/[event]/session/[session]/components/ActionsComponent.tsx, app/[organization]/[event]/session/[session]/components/SessionComponent.tsx, app/[organization]/[event]/stage/[stage]/components/StageLayout.tsx, components/Layout/Navbar.tsx, components/schedule/ScheduleCard.tsx, components/sessions/EmbedSession.tsx, components/sessions/SessionList.tsx
The logic is pretty straight forward. I filter all sessions not only by date, but also stage
What do you think if the hover for the stageModal?
=> Fixed schedule issue, and some minor bugs

app/admin/[organization]/page.tsx
A fix for 500 internal errors on the admin/events page. This was caused by the fetch request not being properly handled and next 13 related issues with fetch.
=> admin-events-fix

data/events/swarm/swarm_winter_solstice.json, packages/app/app/(home)/components/EventCard.tsx, packages/app/app/(home)/components/UpcomingEvents.tsx, packages/app/app/(home)/page.tsx, packages/app/app/[organization]/[event]/(eventHome)/components/LivestreamsSection.tsx, packages/app/app/[organization]/[event]/(eventHome)/page.tsx, packages/app/utils/time.tsx, packages/server/model/event.ts, packages/server/utils.ts
Events will be archived when it is past event day.
Live Preview on the event home page will only show on the event day
=> Auto Archive Events

packages/app/app/[organization]/components/ChannelPlayer.tsx, packages/app/app/[organization]/components/ChannelTabContentItem.tsx, packages/app/app/[organization]/page.tsx, packages/app/app/studio/[organization]/Preview.tsx, packages/app/app/studio/[organization]/clips/page.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/StreamHeader.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/StreamHealth.tsx, packages/app/app/studio/[organization]/livestreams/components/LivestreamTable.tsx, packages/app/app/studio/[organization]/livestreams/components/ShareLivestream.tsx, packages/app/app/studio/[organization]/livestreams/components/ToggleLivestreamVisibility.tsx, packages/app/components/misc/interact/EmbedButton.tsx, packages/app/components/misc/interact/ShareButton.tsx, packages/app/lib/types.ts
fix Share button not working for livestream page
fix: View livestream button takes to a page that does not load the live stream
ft: Add a clip button to livestream page that allow user to access clipping for that livestream
=> channel livestream page bug fixes

.vscode/settings.json, packages/app/app/studio/[organization]/library/[session]/components/EditSessionForm.tsx, packages/app/app/studio/[organization]/library/components/EmptyLibrary.tsx, packages/app/app/studio/[organization]/library/components/GridLayout.tsx, packages/app/app/studio/[organization]/library/components/ListLayout.tsx, packages/app/app/studio/[organization]/library/components/TableCells.tsx, packages/app/app/studio/[organization]/library/components/misc/ProcessingSkeleton.tsx, packages/app/app/studio/[organization]/library/components/upload/UploadVideoForm.tsx, packages/app/app/studio/[organization]/library/page.tsx, packages/app/components/misc/Table/TableSkeleton.tsx, packages/app/components/misc/VideoCard/VideoCardProcessing.tsx, packages/app/components/misc/VideoCard/VideoCardSkeleton.tsx, packages/app/components/misc/VideoCard/VideoCardWithMenu.tsx, packages/app/lib/actions/state.ts, packages/app/lib/services/stateService.ts, packages/server/src/controllers/index.controller.ts, packages/server/src/controllers/state.controller.ts, packages/server/src/dtos/state/create-state.dto.ts, packages/server/src/dtos/state/update-state.dto.ts, packages/server/src/interfaces/state.interface.ts, packages/server/src/models/state.model.ts, packages/server/src/services/state.service.ts
- A state is now created once you upload.
- A loading skeleton is now showing up
=> Asset library improvements

packages/app/app/studio/[organization]/clips/components/CreateClipButton.tsx, packages/app/app/studio/[organization]/clips/page.tsx, packages/app/app/studio/[organization]/event/[eventId]/components/navigation/index.tsx, packages/app/app/studio/[organization]/event/[eventId]/components/stageSettings/multistream/CreateMultistreamTarget.tsx, packages/app/app/studio/[organization]/library/[session]/components/EditSessionForm.tsx, packages/app/app/studio/[organization]/library/components/misc/PopoverActions.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/PublishLivestream.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/StreamHealth.tsx, packages/app/app/studio/[organization]/livestreams/components/EditLivestream.tsx, packages/app/app/studio/[organization]/livestreams/components/LivestreamTable.tsx
- Changed Un-Publish to Unpublish
- Added clearer errors to clipping and disabled button for undefined behavior
- Typos
- Added a ping animation while streaming
- Removed reload on updating a session
- Misalignment of clipping window
=> Fixed minor bugs & multistream

.github/PULL_REQUEST_TEMPLATE/post-mortem.md
This pull request introduces a post-mortem template for pull requests, designed to include all necessary fields for tracking and tracing bugs encountered during development.
This template aims to improve bug documentation and analysis, improve traceability, and promote higher code quality.
=> 📝 post-mortem template for PRs

packages/app/app/api/google/callback/route.ts, packages/app/app/studio/[organization]/library/[session]/components/UploadToYoutubeButton.tsx, packages/app/app/studio/[organization]/library/[session]/page.tsx, packages/app/lib/actions/sessions.ts, packages/app/lib/services/organizationService.tsx, packages/app/lib/services/sessionService.ts, packages/app/lib/types.ts, packages/app/lib/utils/googleAuth.ts, packages/server/src/config/index.ts, packages/server/src/controllers/organization.controller.ts, packages/server/src/controllers/session.controller.ts, packages/server/src/dtos/organization/create-organization.dto.ts, packages/server/src/interfaces/organization.interface.ts, packages/server/src/models/organization.model.ts, packages/server/src/routes/routes.ts, packages/server/src/services/organization.service.ts, packages/server/src/swagger/swagger.json, packages/server/src/utils/oauth.ts, packages/server/src/utils/youtube.ts
✨ This PR introduces the first part of a new feature that allows users to upload videos to YouTube directly from our platform. It includes an upload button, social models for organizations, and a comprehensive flow for adding and managing linked accounts.
Impact
This feature significantly enhances our platform by enabling seamless video uploads to YouTube, improving user engagement and providing a more integrated experience. The new social models for organizations ensure better management and flexibility for linked social media accounts.
User Impact
Users can now upload videos to YouTube through a straightforward interface. When they click the upload button, a modal prompts them to select from their linked accounts or connect a new account. This flow also checks if the user has a YouTube …
=> youtube integrations part 1

packages/app/app/studio/[organization]/clips/components/CreateClipButton.tsx, packages/app/app/studio/[organization]/event/[eventId]/components/stageSettings/multistream/CreateMultistreamTarget.tsx, packages/app/app/studio/[organization]/layout.tsx, packages/app/app/studio/[organization]/library/[session]/components/UploadToYoutubeButton.tsx, packages/app/app/studio/[organization]/library/components/UploadVideoDialog.tsx, packages/app/app/studio/[organization]/library/page.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/Destinations.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/Multistream.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/StreamPlatforms/CreateMultistreamTarget.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/page.tsx, packages/app/app/studio/[organization]/livestreams/components/CreateLivestreamModal.tsx, packages/app/app/studio/[organization]/livestreams/components/EditLivestream.tsx, packages/app/app/studio/[organization]/livestreams/components/LivestreamTable.tsx, packages/app/app/studio/[organization]/nfts/components/CreateNFTCollectionModal.tsx, packages/app/app/studio/[organization]/nfts/create/components/AddMedia.tsx, packages/app/app/studio/[organization]/nfts/create/components/CreateNFTForm.tsx, packages/app/app/studio/[organization]/page.tsx, packages/app/app/studio/[organization]/team/components/AddTeamMembers.tsx, packages/app/components/Sidebar/Sidebar.tsx, packages/app/components/Sidebar/SidebarMenu.tsx, packages/app/components/misc/CopyText.tsx, packages/app/components/ui/button.tsx, packages/app/components/ui/dialog.tsx
=> 🐛 #686 #679 #662 #653

README.md
This PR aims to revert the `develop` branch to a previous stable state due to recent issues.
- 🔙 Rolled back `develop` branch to commit [a2c8ed1b20b5bf30ed34e894db23d8583a448a84](https://github.com/streamethorg/streameth-platform/tree/a2c8ed1b20b5bf30ed34e894db23d8583a448a84)
- 🚀 Preparing for a fresh start from a known good state
=> ⏪ Rollback develop branch to previous stable state

.github/PULL_REQUEST_TEMPLATE/generic_pr.md, .github/PULL_REQUEST_TEMPLATE/post_mortem.md
Created this same PR template and added it to the `.github/PULL_REQUEST_TEMPLATE/` folder
Fixes (#707)
closes #707
=> Generic PR template

packages/app/app/studio/[organization]/library/[session]/components/EditSessionForm.tsx, packages/app/app/studio/[organization]/library/components/misc/PopoverActions.tsx
Commented the delete button found in library to avoid EthCC deleting more clips which will cause unwanted deletion of the whole seesion
Fixes (N/A)
This will be reverted once EthCC finishes
=> 🔥 Commented the delete button

packages/app/app/studio/[organization]/destinations/page.tsx, packages/app/app/studio/[organization]/livestreams/components/LivestreamTable.tsx, packages/app/app/studio/[organization]/page.tsx, packages/app/app/studio/[organization]/settings/page.tsx, packages/app/app/studio/[organization]/team/page.tsx
A fix for #697, which fixes missaligned `Cards`.
closes #697
=> 🐛: Fixed misaligned pages and made pages more consistent

packages/app/app/studio/[organization]/livestreams/[streamId]/components/StreamHealth.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/page.tsx, packages/app/app/studio/[organization]/livestreams/components/ShareLivestream.tsx
- I removed everything form the health component except the healthbadge itself.
- Added a variable in the prototype of the Share button to change the `variant`
- The width was incorrect once live. I force the player to always be 2/3 of the screen
Fixes (#737)
closes #737
=> 🐛: Removed deadcode from healthBadge

packages/server/src/utils/livepeer.ts
=> 🐛 fix multistream bug

packages/app/components/misc/VideoDownloadClient.tsx
Fixed critical bug of the download button not working.
Fixes (#666)
Bug fix (non-breaking change which fixes an issue)
closes #666
=> 🐛: Fixed downloadUrl being an Object instead of a url

packages/app/app/[organization]/watch/page.tsx, packages/app/app/embed/page.tsx, packages/app/app/studio/[organization]/Preview.tsx, packages/app/app/studio/[organization]/clips/page.tsx, packages/app/app/studio/[organization]/library/[session]/page.tsx, packages/app/lib/actions/livepeer.ts, packages/app/lib/services/sessionService.ts
Changed the function `getVideoUrlAction` to not return an non-existing url
Fixes (issue)
#776 
closes #776
=> 🐛: Rewrote the fetchAsset function and changed pages accordingly

packages/app/app/studio/[organization]/library/[session]/components/EditSessionForm.tsx, packages/app/app/studio/[organization]/library/[session]/components/UploadToYoutubeButton.tsx, packages/app/app/studio/[organization]/library/components/misc/PopoverActions.tsx, packages/app/components/Sidebar/SidebarMenu.tsx, packages/app/components/ui/Player.tsx
UnCommented library delete buttons
Fixes (N/A)
=> 💄: Revert - Show Library Delete Buttons & Hide Social upload buttons

packages/app/app/api/google/request/route.ts, packages/app/app/studio/[organization]/livestreams/[streamId]/components/StreamPlatforms/StreamPlatforms.tsx
Update the google auth URL to env for faster debug and update
Fixes (issue)
=> Change google auth url to env

README.md
📝 Update README.md
Changes in detail:
- 🚫 Removed any contribution guidelines to reflect our current stance on external contributions
- 🔗 Added a Typeform link for potential clients to get in touch
- ⚠️ Included a clear warning that the project is not currently set up for external developer contributions
- 🎨 Applied emojis throughout the README to improve readability and visual appeal
- 🔄 Updated the application site link to streameth.org/studio
- 📝 Clarified that while code contributions are not accepted, issue submissions are welcome
closes #839
=> 📝 Improved README.md

packages/server/src/controllers/index.controller.ts, packages/server/src/interfaces/session.interface.ts, packages/server/src/interfaces/state.interface.ts, packages/server/src/models/session.model.ts
"Refactor: Livepeer Webhook and Session Model Enhancements
This pull request refines the Livepeer webhook handling system, focusing on 'asset ready' and 'asset failed' events. 
Key improvements include:
- Updating the Session model to support new propert fields.
- Modifying the state object to accurately reflect current asset status.
These enhancements boost our system's ability to process Livepeer notifications, ensuring better user interactions.
Fixes (#775 )
=> ⚡️ Video processing fix

packages/app/app/speaker/[session]/components/SpeakerYoutubePublishButton.tsx, packages/app/app/speaker/[session]/components/ZoraUploadButton.tsx, packages/app/app/speaker/[session]/page.tsx
Just added full width on mobile for the upload to YouTube and Zora buttons + changed default text of the zora button to be "Upload to zora"
=> 🐛/💄 Minor improvements to the speaker page

packages/app/app/studio/[organization]/clips/components/CreateClipButton.tsx, packages/app/app/studio/[organization]/library/components/LibraryListLayout.tsx, packages/app/app/studio/[organization]/library/components/TableCells.tsx, packages/app/app/studio/[organization]/library/components/misc/VideoCardWithMenu.tsx, packages/app/app/studio/[organization]/library/page.tsx, packages/app/lib/utils/utils.ts, packages/server/src/dtos/session/update-session.dto.ts, packages/server/src/interfaces/session.interface.ts, packages/server/src/models/session.model.ts, packages/server/src/routes/routes.ts, packages/server/src/swagger/swagger.json, packages/server/src/utils/livepeer.ts
Import sessions will now have the date when clipped as Created At instead of the import date.
Also, I changed the video information display date to CreatedAt to showcase when the video was originally uploaded.
Fixes #869 
closes #869
=> ⚡Replace UpdateAt with CreatedAt and update clipping date

packages/app/app/studio/(home)/components/CreateOrganizationForm.tsx, packages/app/app/studio/[organization]/library/components/upload/Dropzone.tsx, packages/app/components/misc/form/imageUpload.tsx
My last PR (#865) improved the image uploading UX. Those fixes were apparently breaking the forms. I reread the documentation of `react-dropzone` and hopefully found a solution. The automatic and manual tests work as they normally do.
Fixes #902
=> 🐛: Resolve form compatibility issues in ImageUpload component

packages/app/app/studio/[organization]/library/[session]/page.tsx, packages/app/app/studio/[organization]/library/components/TableCells.tsx, packages/app/components/misc/VideoDownloadClient.tsx
Bring back generate transcription button in library
The generate transcription button allows users to request transcriptions of old videos. Transcriptions are auto-generated for new videos.
=> ⚡revert changes made to studio session page

packages/server/src/controllers/index.controller.ts, packages/server/src/interfaces/state.interface.ts, packages/server/src/models/state.model.ts, packages/server/src/services/session.service.ts, packages/server/src/services/state.service.ts, packages/video-uploader/src/audio-queue.ts, packages/video-uploader/src/utils/errors.ts, packages/video-uploader/src/utils/youtube.ts, packages/video-uploader/src/video-queue.ts
Enhance Transcription Processing with Improved State Management and Feedback
This PR introduces significant improvements to the transcription processing workflow:
1. Implements a new 'processing' state that is set upon transcription initialization.
2. Enhances the update mechanism for session states, now pulling the latest information directly from the video server.
These enhancements provide better visibility into the transcription status and ensure more accurate state representation throughout the process.
- Conducted comprehensive integration tests to verify the new state management flow.
- Performed manual testing to ensure the correct state transitions and updates from the video server.
- Verified that the 'processing' state is correctly set and updated throughout the transcription …
=> ⚡️ Transcription Processing

packages/server/src/controllers/index.controller.ts
Fix the Wrong key value when updating state session
Caused webhook failure when updating session state
=> 🐛 hotfix: Webhook state fix for sessions

packages/app/app/studio/[organization]/clips/components/CreateClipButton.tsx, packages/server/src/controllers/index.controller.ts, packages/server/src/controllers/stage.controller.ts, packages/server/src/services/schedule-import.service.ts, packages/server/src/services/session.service.ts, packages/server/src/utils/google-sheet.ts, packages/server/src/utils/livepeer.ts
Enhance App State Management and Livepeer Webhook Handling
This PR addresses multipe issues and improves the overall state management of the application
1. State Creation for Clips:
- Implements proper state transitions for new clips.
- Ensures the clipping process includes all necessary states (e.g., processing, completed).
2.  Livepeer Webhook Payload Handling:
- Handling potential null values in the Livepeer webhook payload.
3. Stream Recording Updates:
- Updates session names for stream recordings.
- Resolves an issue where the clipping process incorrectly skipped states, moving directly to completed.
- Enhances data consistency for stream recordings.
- Thoroughly tested the clip creation process to verify correct state transitions.
- Verified session name updates for various stream …
=> 🐛 hotfix: Webhook state fix for clips & sessions

packages/app/app/studio/[organization]/library/[session]/components/UploadToYoutubeButton.tsx, packages/app/app/studio/[organization]/library/[session]/components/UploadTwitterButton.tsx, packages/app/app/studio/[organization]/library/[session]/page.tsx, packages/app/lib/actions/sessions.ts, packages/app/lib/services/sessionService.ts, packages/server/src/controllers/index.controller.ts, packages/server/src/models/session.model.ts, packages/server/src/services/session.service.ts, packages/server/src/utils/livepeer.ts, packages/video-uploader/src/utils/twitter.ts, packages/video-uploader/src/video-queue.ts
Twitter Upload for Sessions Up to 140 Seconds
This PR implements Twitter upload functionality for sessions with a duration of up to 2 minutes and 20 seconds (140 seconds) due to Twitter restrictions.
- Implemented Twitter API integration for video uploads
- Added validation for video duration (max 140 seconds)
- Refactored existing upload logic to accommodate Twitter's requirements
- Manual testing conducted with various video lengths:
- Videos under 140 seconds: Successfully uploaded
- Videos over 140 seconds: Appropriate error message displayed
- Integration tests performed to ensure proper API communication
- Users can now directly upload videos to Twitter from our platform
- Improved user experience for social media sharing
Closes #703, #925
=> Twitter upload

packages/app/components/Sidebar/SidebarMenu.tsx
Just removed the NFT access, it add visual clutter to the sidebar, no event is actually asking for this, it is a feature that doesnt add value to the platform.
We will have Zora upload button instead.
=> 💄 Removed access to the NFTs feature

packages/app/app/studio/[organization]/livestreams/components/EditLivestream.tsx, packages/app/components/misc/interact/InfoHoverCard.tsx, packages/app/components/sessions/SessionInfoBox.tsx, packages/app/lib/utils/time.tsx, packages/app/lib/utils/timezone.tsx, yarn.lock
Improve timezone handling and UI for event creation
This PR addresses issues with timezone handling in the event creation process and improves the UI to make it more user-friendly. The main changes include:
1. Updated the TimePicker component to clearly indicate that users should enter the event time in their local timezone.
2. Added a feature to show the equivalent UTC time based on the user's input for immediate feedback.
These changes aim to reduce confusion around timezone entry and improve the overall user experience when creating events.
- Tested the TimePicker component with various timezone offsets to ensure correct conversion to UTC.
- Verified that the InfoHoverCard displays the correct user timezone and instructions.
- Checked that the UTC time display updates correctly as the …
=> 🐛: Missing Timezone Information for Scheduled Streams

packages/app/tests/organizationHome.spec.ts
I made sure I am reloading specific things in the tester by my self
=> 🐛: Minor improvement on testing

packages/server/src/interfaces/livepeer.webhook.interface.ts, packages/server/src/services/session.service.ts
#Fix StreamRecordings 
This PR addresses the issue with stream recordings that were associated with incorrect `stageId` values. It also implements error handling for invalid stage.
=> Fix stream recordings

packages/app/app/studio/[organization]/library/components/TableCells.tsx
Merging to be able to add some changes related to the clipping page like:
Adding a clip button in the library page for recordings
=> ✨ Showing a clip button for recording less than 7 days old in library

packages/app/app/studio/[organization]/clips/[stageId]/Player.tsx, packages/app/app/studio/[organization]/clips/[stageId]/Timeline/index.tsx, packages/app/app/studio/[organization]/clips/[stageId]/topBar/CreateClipButton.tsx, packages/app/app/studio/[organization]/clips/page.tsx, packages/app/app/studio/[organization]/library/components/TableCells.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/ClipsList.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/page.tsx
Quick merge with latest changes done while testing the clipping page rework branch
Manual testing of all new and previous additions
=> Clipping page rework latest changes

packages/app/app/studio/[organization]/livestreams/[streamId]/components/ClipsList.tsx, packages/app/app/studio/[organization]/livestreams/components/DeleteLivestream.tsx, packages/app/app/studio/[organization]/livestreams/components/EditLivestream.tsx, packages/app/app/studio/[organization]/livestreams/components/LivestreamActions.tsx, packages/app/components/misc/interact/ShareButton.tsx
Implementing some UI suggestions from pablo
https://github.com/user-attachments/assets/7a79c66e-a787-47fb-b558-f10d5e3a92e5
=> 💄 Feedback on latest prod changes by pablo

packages/app/app/studio/[organization]/clips/[stageId]/Controls/index.tsx, packages/app/app/studio/[organization]/clips/[stageId]/Timeline/index.tsx, packages/app/app/studio/[organization]/clips/[stageId]/page.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/markers/PushMarkersButton.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/markers/index.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/ClipsList.tsx, packages/app/app/studio/[organization]/livestreams/components/DeleteLivestream.tsx, packages/app/app/studio/[organization]/livestreams/components/EditLivestream.tsx, packages/app/app/studio/[organization]/livestreams/components/LivestreamActions.tsx, packages/app/components/misc/interact/ShareButton.tsx
=> Merge dev to main

packages/app/app/studio/[organization]/clips/[stageId]/Timeline/index.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/clips/index.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/index.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/markers/Marker.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/markers/index.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/Multistream.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/Sidebar.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/StreamConfigWithPlayer.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/StreamPlatforms/CreateMultistreamTarget.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/page.tsx
Change some details on the stream page
[Provide a detailed explanation of the changes you have made. Include the reasons behind these changes and any relevant context. Link any related issues.]
[Detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]
[Discuss the impact of your changes on the project. This might include effects on performance, new dependencies, or changes in behaviour.]
=> 💄Stream page ui changes

packages/app/app/studio/[organization]/clips/[stageId]/Timeline/index.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/clips/index.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/index.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/markers/Marker.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/markers/index.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/Multistream.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/Sidebar.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/StreamConfigWithPlayer.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/StreamPlatforms/CreateMultistreamTarget.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/page.tsx
=> Small UI improvements for stream page

packages/app/app/studio/[organization]/clips/[stageId]/sidebar/clips/Preview.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/clips/index.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/index.tsx, packages/app/lib/utils/utils.ts
I messed up when trying to fix #989, clips should now show just like they did before
=> 🚑️ Fixed the clips not showing (sorry my bad hehe)

packages/app/next.config.js
🐛 Hotfix for the images optimization.
[As states in the next docs](https://nextjs.org/docs/app/api-reference/components/image#unoptimized)
```
module.exports = {
images: {
unoptimized: true,
},
}
```
=> 🐛 Hotfix images with main base

packages/server/package.json, yarn.lock
Update Build Scripts to Copy Email Templates
This PR fixes the issue of missing templates folder after the build process.
=> 📦️ update build script to copy templates to dist folder

packages/server/src/services/session.service.ts, packages/video-uploader/src/utils/youtube.ts, packages/video-uploader/src/video-queue.ts
=> 🐛 Hotfix youtube upload

packages/app/app/studio/[organization]/clips/[stageId]/sidebar/clips/index.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/index.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/markers/index.tsx, packages/app/app/studio/[organization]/layout.tsx, packages/app/components/misc/Support/index.tsx
fixed #989 again, might have been overwritten somehow + removed the floating support form.
Manual testing as seen in the video
https://github.com/user-attachments/assets/6d0e1b76-63b7-4eec-a99c-d3ec51c61217
=> Markers sidebar broken again

packages/app/app/studio/(home)/components/CreateOrganizationForm.tsx, packages/app/app/studio/(home)/page.tsx, packages/app/app/studio/[organization]/library/[session]/components/ImageDropzone.tsx, packages/app/components/misc/form/imageUpload.tsx, packages/app/lib/utils/resizeImage.ts
Removed restrictions when uploading a banner and handle the resizing of the images
Manual testing as seen in the video
User now wont find that annoying creating a new organization.
https://github.com/user-attachments/assets/25bf1261-e582-486f-8bd6-eacaa92bea32
=> 💄/🐛 Improved banner upload UX based on user feedback

packages/app/app/studio/[organization]/clips/[stageId]/ClipContext.tsx, packages/app/app/studio/[organization]/clips/[stageId]/Controls/index.tsx, packages/app/app/studio/[organization]/clips/[stageId]/Timeline/TrimmControls.tsx, packages/app/app/studio/[organization]/clips/[stageId]/Timeline/index.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/clips/Clip.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/markers/AddOrEditMarkerForm.tsx, packages/app/app/studio/[organization]/clips/[stageId]/topBar/CreateClipButton.tsx, packages/app/lib/utils/utils.ts
Add keyboard shortcuts to video editor
closes #1014
`-` for Zoom out
`+` for Zoom In
`0` for Fit
`i` for trim In
`o` for trim out
Faster clipping
=> ⚡️ Add keyboard shortcuts to video editor

packages/app/app/studio/[organization]/clips/[stageId]/Controls/KeyboardShortcuts.tsx, packages/app/app/studio/[organization]/clips/[stageId]/Controls/index.tsx, packages/app/app/studio/[organization]/clips/[stageId]/Timeline/index.tsx
Add new keyboard shortcuts
`k` Pause/play in player.
`r` Reset slider.
`j` Speed up the video playback rate.
`l` Slow down the video playback rate.
`h` Reset video playback rate.
`ArrowLeft` Seek backward a second in player.
`ArrowRight` Seek forward a second in player.
`Shift+ArrowLeft` Seek backward 10 seconds in player.
`Shift+ArrowRight` Seek forward 10 seconds in player.
=> New keyboard shortcuts

packages/app/app/studio/[organization]/clips/[stageId]/Controls/KeyboardShortcuts.tsx, packages/app/app/studio/[organization]/clips/[stageId]/Controls/index.tsx
=> 🐛 Fix playback select input

packages/app/app/studio/[organization]/event/[eventId]/components/stageSettings/StageConfig.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/StreamConfigWithPlayer.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/page.tsx, packages/app/lib/utils/generateGoogleCalendar.ts
SRT is a protocol with additional features to stream. I am currently testing scenarios where we would need to use SRT.
The Edge City would like to have GCalendar working again 
- I tested in a few different timezones, and it works perfectly
- The SRT works
=> Add SRT Support and fixed GCalendar reminder for an upcoming stream

packages/app/app/studio/[organization]/clips/[stageId]/topBar/CreateClipForm.tsx, packages/app/app/studio/[organization]/library/components/misc/ProcessingSkeleton.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/StageControls.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/StreamConfigWithPlayer.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/StreamHealth.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/page.tsx, packages/server/src/controllers/index.controller.ts, packages/server/src/services/session.service.ts
=> refactor live stage controls

packages/app/app/studio/[organization]/clips/[stageId]/page.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/clips/Clip.tsx, packages/server/src/controllers/index.controller.ts, packages/server/src/interfaces/clip.editor.interface.ts, packages/server/src/interfaces/clip.interface.ts, packages/server/src/interfaces/state.interface.ts, packages/server/src/models/clip.editor.model.ts, packages/server/src/utils/job-worker.ts, packages/server/src/utils/livepeer.ts
=> Clipeditor state

packages/app/app/[organization]/components/WatchGrid.tsx, packages/app/app/[organization]/videos/components/ArchiveVideos.tsx, packages/app/app/[organization]/videos/page.tsx, packages/app/app/studio/[organization]/library/page.tsx, packages/app/lib/data.ts, packages/app/lib/services/sessionService.ts, packages/server/src/controllers/session.controller.ts, packages/server/src/routes/routes.ts, packages/server/src/services/session.service.ts, packages/server/src/swagger/swagger.json, packages/video-uploader/src/utils/twitter.ts
Visibility not properly set to `string` everywhere
=> 🐛 Visibility field set to string everywhere

packages/app/app/[organization]/videos/components/eventSelect.tsx, packages/app/app/studio/[organization]/clips/[stageId]/topBar/CreateClipForm.tsx, packages/app/app/studio/[organization]/clips/[stageId]/topBar/SelectAnimation.tsx, packages/app/app/studio/[organization]/components/SwitchOrganization.tsx, packages/app/app/studio/[organization]/library/[session]/components/SessionTranscriptions.tsx, packages/app/app/studio/[organization]/library/components/misc/ProcessingSkeleton.tsx, packages/app/app/studio/[organization]/nfts/components/MintNftSort.tsx, packages/app/components/misc/CopyText.tsx, packages/app/components/misc/interact/EmbedButton.tsx, packages/app/components/ui/combo-box.tsx
1. Change marker and animation select to Combox on clip page
2. Add session id to processing video in the library
=> ♻️ make edit clip form selections a combobox

packages/app/app/studio/[organization]/library/[session]/components/UploadToDevcon.tsx, packages/app/lib/services/pipedreamService.ts, packages/server/src/controllers/index.controller.ts, packages/server/src/dtos/pipedream/pipedream.dto.ts, packages/server/src/interfaces/pipedream.interface.ts, packages/server/src/routes/routes.ts, packages/server/src/swagger/swagger.json
Added vtt link and whole text to the devcon api call
=> Transcripts for devcon

packages/app/app/studio/[organization]/clips/[stageId]/sidebar/markers/AddOrEditMarkerForm.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/markers/PushMarkersButton.tsx, packages/app/lib/schema.ts, packages/server/src/dtos/marker/update-marker.dto.ts, packages/server/src/routes/routes.ts, packages/server/src/swagger/swagger.json
Fix pretalx code not getting update when updating marker and also fix push marker bug on some markers
[Provide a detailed explanation of the changes you have made. Include the reasons behind these changes and any relevant context. Link any related issues.]
[Detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]
[Discuss the impact of your changes on the project. This might include effects on performance, new dependencies, or changes in behaviour.]
=> Marker update

packages/app/app/studio/[organization]/clips/[stageId]/sidebar/markers/AddOrEditMarkerForm.tsx, packages/app/app/studio/[organization]/clips/[stageId]/sidebar/markers/PushMarkersButton.tsx, packages/app/lib/schema.ts, packages/server/src/dtos/marker/update-marker.dto.ts, packages/server/src/routes/routes.ts, packages/server/src/swagger/swagger.json
Sync Dev
Fix pretalx code not getting update when updating marker and also fix push marker bug on some markers
=> Dev to main, (Fix pretalx code not getting update when updating marker and also fix push marker bug on some markers)

packages/app/app/[organization]/components/WatchGrid.tsx, packages/app/app/[organization]/livestream/page.tsx, packages/app/app/[organization]/page.tsx, packages/app/app/[organization]/videos/components/ArchiveVideos.tsx, packages/app/app/[organization]/videos/page.tsx, packages/app/app/[organization]/watch/page.tsx, packages/app/app/studio/[organization]/clips/[stageId]/page.tsx, packages/app/components/misc/Videos.tsx, packages/app/lib/services/sessionService.ts, packages/server/src/controllers/session.controller.ts
[Provide a succinct and descriptive title for the pull request, e.g., "Improve caching mechanism for API calls"]
Because of some refactoring we renamed `organization` to `organizationId` on the backend. We did not correctly set the name on the front-end
=> 🚑 Fixed issue of trying to fetch organizationSlug instead of organizationId

packages/app/components/Layout/HomePageNavbar.tsx
=> 🐛: Fixed logo on mobile

packages/app/app/[organization]/components/WatchGrid.tsx, packages/app/app/[organization]/livestream/page.tsx, packages/app/app/[organization]/page.tsx, packages/app/app/[organization]/videos/components/ArchiveVideos.tsx, packages/app/app/[organization]/videos/page.tsx, packages/app/app/[organization]/watch/page.tsx, packages/app/app/studio/[organization]/clips/[stageId]/page.tsx, packages/app/components/Layout/HomePageNavbar.tsx, packages/app/components/misc/Videos.tsx, packages/app/lib/services/sessionService.ts, packages/server/src/controllers/session.controller.ts
- Sessions fetch hotfix
- Fixed incorrect logo size bug
=> Merge develop to main

packages/app/components/ui/Player.tsx
[Provide a succinct and descriptive title for the pull request, e.g., "Improve caching mechanism for API calls"]
[Provide a detailed explanation of the changes you have made. Include the reasons behind these changes and any relevant context. Link any related issues.]
[Detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]
[Discuss the impact of your changes on the project. This might include effects on performance, new dependencies, or changes in behaviour.]
=> 🔥hotfix: captions on player crashing safari playback

packages/app/app/[organization]/livestream/components/CalendarReminder.tsx, packages/app/app/[organization]/livestream/page.tsx, packages/app/app/speaker/[session]/components/ZoraUploadButton.tsx, packages/app/app/studio/[organization]/clips/[stageId]/ClipContext.tsx, packages/app/app/studio/[organization]/components/UserProfile.tsx, packages/app/app/studio/[organization]/library/components/Library.tsx, packages/app/app/studio/[organization]/library/components/LibraryFilter.tsx, packages/app/app/studio/[organization]/library/components/Pagination.tsx, packages/app/auth.ts, packages/app/components/misc/SearchBar/index.tsx, packages/app/components/sessions/InfoBoxDescription.tsx, packages/app/components/sessions/SessionInfoBox.tsx, packages/app/tests/utils/removeStages.ts, packages/app/tests/utils/setFile.ts, packages/server/src/services/session.service.ts
Filter by visibility was not working due to the change on the visibility data type, which was before a boolean, and now is an enum.
The search bar results was showing both the "type":"clip" and "type":"editorClip" results.
Some swarm modifications added to link the google calendar link to their specified link
added back the green check when a filter si selected
=> 🚑/🐛 fix filter by visibility + search showing editorClips

packages/app/app/studio/[organization]/team/components/AddTeamMembers.tsx, packages/app/app/studio/[organization]/team/page.tsx, packages/app/lib/actions/organizations.ts, packages/app/lib/services/organizationService.tsx, packages/server/src/dtos/user/user.dto.ts, packages/server/src/interfaces/user.interface.ts, packages/server/src/models/user.model.ts, packages/server/src/services/organization.service.ts, packages/server/src/services/user.service.ts, packages/server/src/utils/mail.service.ts, packages/server/src/utils/util.ts, packages/server/templates/invite.html
To make the user experience smoother, the invitation is now send as an email to both existing and not existing users.
- Invited a non-existing user
- Invited a existing user
=> ✨ (new) Users get an email on invitation to an organization

packages/app/app/[organization]/components/UpcomingStreams.tsx, packages/app/app/studio/[organization]/components/UserProfile.tsx, packages/app/app/studio/[organization]/livestreams/[streamId]/components/StageControls.tsx, packages/app/app/studio/[organization]/livestreams/components/DeleteLivestream.tsx, packages/app/app/studio/[organization]/livestreams/components/EditLivestream.tsx, packages/app/app/studio/[organization]/livestreams/components/LivestreamActions.tsx, packages/app/app/studio/[organization]/livestreams/components/LivestreamTable.tsx, packages/app/app/studio/[organization]/livestreams/components/ShareLivestream.tsx, packages/app/app/studio/[organization]/livestreams/components/ToggleLivestreamVisibility.tsx, packages/app/app/studio/[organization]/page.tsx, packages/app/components/Layout/HomePageNavbar.tsx, packages/app/components/Layout/NavbarStudio.tsx, packages/app/components/misc/interact/ShareButton.tsx, packages/app/lib/services/stageService.tsx, packages/server/src/services/stage.service.ts
Fixed multiple issues related to stream visibility and component rendering:
- Added missing action functionality for toggling stream visibility state
- Fixed component alignment and styling consistency
- Resolved server/client component rendering conflict
- Corrected backend filtering logic to use stream date instead of creation date
=> 🐛 Improve Stream Visibility and Date Filtering

packages/app/app/studio/[organization]/(no-side-bar)/clips/[stageId]/sidebar/clips/Clip.tsx, packages/app/app/studio/[organization]/(no-side-bar)/clips/[stageId]/topBar/CreateClipButton.tsx, packages/app/app/studio/[organization]/(no-side-bar)/clips/[stageId]/topBar/SelectAnimation.tsx, packages/app/components/misc/UserProfile.tsx, packages/app/components/misc/form/videoUpload.tsx, packages/app/lib/actions/imageUpload.ts, packages/app/lib/actions/sessions.ts, packages/app/lib/actions/videoUpload.ts, packages/app/lib/services/sessionService.ts, packages/app/lib/services/videoUploadService.ts, packages/server/src/app.ts, packages/server/src/controllers/index.controller.ts, packages/server/src/databases/index.ts, packages/server/src/dtos/stream/create-clip.dto.ts, packages/server/src/interfaces/clip.editor.interface.ts, packages/server/src/interfaces/clip.interface.ts, packages/server/src/middlewares/multer.middleware.ts, packages/server/src/models/clip.editor.model.ts, packages/server/src/routes/routes.ts, packages/server/src/services/clipEditor.service.ts, packages/server/src/services/session.service.ts, packages/server/src/swagger/swagger.json, packages/server/src/utils/s3.ts, packages/server/src/utils/validateWebhook.ts, packages/server/workers/clips/index.ts, packages/video-uploader/src/config/index.ts
Intro animations now get uploaded to s3 instead of Livepeer to avoid the processing time from Livepeer
=> Fix intro animations

packages/server/src/services/session.service.ts
The server now at least builds on local
=> 🚑 fixed build

packages/reel-creator/remotion/Editor/Editor.tsx
When creating a vertical aspect ratio and adding captions, captions didnt appear, now they do
=> 🐛 captions + tiktok fix

packages/app/app/studio/[organization]/(no-side-bar)/clips/[stageId]/sidebar/clips/CreateClipForm.tsx, packages/app/components/misc/UserProfile.tsx, packages/app/components/misc/form/videoUpload.tsx, packages/app/lib/services/fetch-client.ts, packages/app/lib/services/sessionService.ts, packages/app/lib/services/videoUploadService.ts, packages/server/src/app.ts, packages/server/src/services/session.service.ts
Added some logs to see why animations are not being uploaded + fixed the combobox bug where animations wouldnt show
=> Animaiton fixes

packages/app/app/studio/[organization]/(root)/library/[session]/components/EditSessionForm.tsx, packages/app/app/studio/[organization]/(root)/library/[session]/components/form/BasicFormFields.tsx, packages/app/app/studio/[organization]/(root)/library/[session]/components/form/FormActions.tsx, packages/app/app/studio/[organization]/(root)/library/[session]/components/form/ThumbnailSection.tsx, packages/app/app/studio/[organization]/(root)/library/[session]/components/form/VisibilitySelector.tsx, packages/app/app/studio/[organization]/(root)/library/[session]/components/form/utils.ts, packages/app/components/misc/form/imageUpload.tsx, packages/server/src/controllers/stream.controller.ts, packages/server/src/utils/livepeer.ts
Added a generate thumbnail button in the session form and heavily improved UX when handling session thumbnails.
Worked on a refactor of the session form component to make it into separate components.
=> Get thumbnail buttons + `EditSessionForm.tsx` refactor

packages/server/src/utils/livepeer.ts
Seems very random what type of default image livepeer gives us...
=> 🚑 Added jpeg as possible image source

packages/app/app/studio/[organization]/(no-side-bar)/clips/[stageId]/Timeline/TrimmControls.tsx, packages/app/app/studio/[organization]/(no-side-bar)/clips/[stageId]/sidebar/Transcipts/index.tsx, packages/app/app/studio/[organization]/(no-side-bar)/clips/[stageId]/sidebar/index.tsx, packages/app/app/studio/[organization]/(root)/team/page.tsx, packages/server/src/controllers/index.controller.ts, packages/server/src/services/stage.service.ts
💄 When on preview mode, a yellowish color will replace the trimmcontrols red default color.
🐛 Double scrollbar in transcribe tab fixed
🐛 Members list is now scrollable
🐛 Fixed stream.idle webhook handling
=> 💄 Various fixes

packages/app/app/[organization]/components/UpcomingStreams.tsx, packages/app/app/[organization]/page.tsx, packages/app/app/studio/(home)/create/page.tsx, packages/app/app/studio/(home)/page.tsx, packages/app/app/studio/[organization]/(root)/page.tsx, packages/app/app/studio/[organization]/layout.tsx, packages/app/lib/context/UserContext.tsx
---
This pull request introduces a new feature to display an active live stream directly on the organization's main channel page (`app/[organization]/page.tsx`). If an organization has a stream that is currently live (`streamSettings.isActive === true`), a player component will be rendered at the top of the page instead of the standard channel banner.
Key changes include:
**Feature Implementation (`app/[organization]/page.tsx`):**
- Added `"use server";` directive.
- Fetches organization stages (streams) on page load.
- Implements logic to find the first `liveStream` from the fetched stages.
- Conditionally renders a new `Player` component if a `liveStream` is active; otherwise, displays the existing `ChannelBanner`.
- The default active tab is now dynamically set to "livestreams" …
=> ✨ Feature: Display Live Player on Organization Page & Refactor Studio Create Page
