streamethorg/streameth-platform

- app/admin/components/AdminWrapper.tsx
- app/utils/ClientOnly.tsx
- server/utils.ts
Added a ClientOnly component at the root folder, this is to check whether we are in server-side rending or client-side rendering, if our application has not mounted, this will return null otherwise return children, this will fix NextJs hydration error on the client side.
> Hydration-fix

- packages/app/app/[organization]/[event]/schedule/components/DateSelect.tsx
- packages/app/app/[organization]/[event]/schedule/components/ScheduleCard.tsx
- packages/app/app/[organization]/[event]/schedule/components/ScheduleComponent.tsx
- packages/app/components/sessions/SessionList.tsx
- packages/app/lib/context/SiweContext.tsx
- packages/app/lib/utils/time.tsx
This pull request addresses the issue with the schedule date filter on the event page. Previously, the date filter was based on the date range between the start and end of an event, which resulted in including days without sessions in the date filter. The updated approach uses session dates to determine the dates displayed in the filter, ensuring that only dates with sessions are included.
Additionally, the filter now supports filtering by all dates if multiple dates exist for an event. This enhancement allows users to filter events based on all available dates associated with the event.
> Feat: Filter Schedule by Session Dates

- packages/app/components/authorization/AuthorizationMessage.tsx
- packages/app/components/misc/ConnectWalletButton.tsx
- packages/app/lib/utils/metadata.ts
- packages/app/next.config.js
This PR configures the manual CDN to use a custom asset prefix only in production and added minor optimization to auth
> Handle asset prefix on local 

- packages/app/app/[organization]/livestream/components/Counter.tsx
- packages/app/app/[organization]/livestream/components/Player.tsx
- packages/app/app/studio/[organization]/library/components/DeleteAsset.tsx
- packages/app/app/studio/[organization]/library/components/UploadVideoDialog.tsx
Bugfixes
- See #644
- Changed `location.reload` to `router.refresh`
> router.refresh(): Refresh the current route. Making a new request to the server, re-fetching data requests, and re-rendering Server Components. The client will merge the updated React Server Component payload without losing unaffected client-side React (e.g. useState) or browser state (e.g. scroll position).
> Fixed counter issue

- packages/app/app/studio/[organization]/clips/components/CreateClipButton.tsx
- packages/app/app/studio/[organization]/library/page.tsx
- packages/server/src/controllers/index.controller.ts
- packages/server/src/interfaces/livepeer.interface.ts
- packages/server/src/interfaces/state.interface.ts
I reverted a few changes that were breaking the library. It now creates an `state` once the clip has been created. Showing it on the library page while processing.
I also added a untested webhook if the video has failed to process. We will have to wait until Livepeer fails to process once to examine the webhook.
Fixes (issue)
#769 
> 🐛: Reverted changes on the library page and added state logic to clipping page

- packages/app/components/misc/SignInUserButton.tsx
When signing in, if you were to click in the sign-out button, the app wasn't able to properly handle the state and would get stuck.
-    **Services Affected**: Sign in flow
-    **User Impact**: Could generate bad UX if user sees a completely frozen app
No loading state handling from the front-end
Properly handle the loading state + making the user actually sign-out if it clicks the sign-out button
1. Whenever we need to have a loading state, properly use the `useState` hook
https://github.com/user-attachments/assets/13980207-10f9-4d66-9138-905ae7f2a0ba
closes #637 
**Reviewer Checklist:**
-    [ ] Incident details are complete
-    [ ] Root cause is clearly defined
-    [ ] Resolution steps are clearly detailed
-    [ ] Related 🐛 issues are provided
> 🐛 Fix the sign-in flow getting stuck when quickly clicking sign-out

- packages/app/components/misc/form/imageUpload.tsx
In PR #814 I introduced a bug where when delting the banner and updating the organization, i was sending `null` instead of `' '` to the backend, and `null` is not supported on our organization schema (which makes total sense)
Fixes (#818)
https://github.com/user-attachments/assets/a0cf68c6-9426-4bdf-ae75-337f8fb52e46
closes #818
> 🐛 Fixes #818

- packages/app/components/authorization/AuthorizationMessage.tsx
- packages/app/components/misc/ConnectWalletButton.tsx
- packages/app/components/misc/SignInUserButton.tsx
- packages/app/components/ui/button.tsx
- packages/server/src/services/auth.service.ts
This PR enhances user onboarding by disabling account creation for new users on the login screen, updating the event onboarding page to offer options to either create an event or explore, and modifying the login screen to allow existing users to log in normally while presenting new users with a modal with a create event button that initiates the account creation flow.
> ✨ Fix #807 - Improve the user onboarding experience

- packages/app/app/api/google/request/route.ts
- packages/app/app/studio/[organization]/livestreams/[streamId]/components/StreamPlatforms/StreamPlatforms.tsx
There was an issue where if you already granted permission for google to manage your YT then it wouldn't do it again and redirect wouldn't work.
Fixes (none)
This didn't happen on `localhost` but it did happen on dev
> ⚡️ Update Youtube Permissions

- packages/app/app/studio/[organization]/destinations/page.tsx
- packages/app/components/misc/ConnectWalletButton.tsx
- packages/server/src/dtos/session/upload-session.dto.ts
- packages/server/src/interfaces/upload.session.interface.ts
- packages/server/src/routes/routes.ts
- packages/server/src/services/session.service.ts
- packages/server/src/swagger/swagger.json
- packages/video-uploader/package.json
- packages/video-uploader/src/utils/twitter.ts
- packages/video-uploader/src/utils/youtube.ts
- packages/video-uploader/src/video-queue.ts
- yarn.lock
This pull request integrates the Twitter Media Upload API and Tweet API, enabling users to publish videos from the studio page to Twitter. The media upload process is divided into three phases:
- Initialize: Send media type, command, and byte size to receive a media_id.
- Append Phase: Split the video file into base64 chunks (≤ 5MB each) and send them to Twitter.
- Finalize: Complete the media upload and process the video.
Closes (#782 )
Twitter's media upload limits apply:
- Video duration: 0.5 seconds to 140 seconds (https://developer.x.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices)
- Refer to [Twitter Media Upload API documentation](https://developer.x.com/en/docs/twitter-api/v1/media/upload-media/api-reference/post-media-upload-init) for more …
> ✨ Twitter upload integration

- packages/app/components/misc/Support/SupportForm.tsx
- packages/app/components/misc/Support/index.tsx
- packages/app/components/misc/form/imageUpload.tsx
- packages/app/lib/actions/support.ts
- packages/app/lib/services/supportService.tsx
- packages/server/src/services/support.service.ts
1. Support form creates some super weird interaction when you click on the delete image icon, which is caused by the delete confirmation dialog been hidden behind the support form dialog.
2. Fix Telegram bot returning undefined in the support channel due to wrong form data sent to the backend
-    **Services Affected**: Support form, Telegram bot integration
-    **User Impact**: Users experienced issues with deleting images in the support form, and Telegram bot messages were not being sent correctly, leading to communication gaps in the support channel.
1. Hidden Delete Confirmation Dialog: The delete confirmation dialog was hidden behind the support form dialog. This was due to incorrect z-index settings in the CSS, causing the dialog to be non-interactive and confusing users.
2. …
> 🐛 fix: support form image bug and telegram bot returns undefined

- packages/server/src/utils/livepeer.ts
Livepeer updated their thumbnail generation without any notice. Luckily they simply changed from `jpg` to `png`
Fixes (not-tracked)
> 🐛 Updated the thumbnail generation from .jpg to .png

- packages/server/src/interfaces/stage.interface.ts
- packages/server/src/models/stage.model.ts
- packages/server/src/services/session.service.ts
Please include a summary of the change and which issue is fixed, or which feature has been implemented.
closes #890 
This PR addresses unintuitive naming for recordings by introducing a recordingIndex on the stage model, which auto-increments after each session is generated.
> ✨ feat: Add recordingIndex field to IStage interface and StageSchema

- packages/app/app/[organization]/components/ChannelDescription.tsx
- packages/app/app/[organization]/page.tsx
- packages/app/app/studio/[organization]/clips/components/CreateClipButton.tsx
- packages/app/app/studio/[organization]/library/[session]/page.tsx
- packages/app/components/ui/combo-box.tsx
- Trucated Long titles overflow modal on clip page
- Break-words on Organization description overflows X-axis in banner
closes #862 closes #875 closes #876
> 🐛 fix Long titles overflow modal on clip page and overflow text on organization description

- .github/workflows/playwright.yml
Due to a breaking change introduced in https://github.com/actions/upload-artifact/issues/602. Adjusted job configuration to ensure the job to run by considering hidden files.
> Fixed breaking change of GA Artifacts

- packages/app/app/studio/(home)/page.tsx
- packages/app/components/Layout/HomePageNavbar.tsx
If the user only has 1 org, directly redirecting there improves UX quite a lot 
Still didn't test this, can't seem to create a new user even though I did directly add it to Privy console... I'm missing something here.
Quicker user redirects to the actual product.
We need to include a `Create Organization` button somewhere else in the UI for users only with one Org, as there no other way of creating a new Org. Once the user creates a new org, we can make that button not visible to the user so we do not add too much clutter.
> 💄 If only 1 org, instantly redirect there

- packages/app/app/studio/[organization]/livestreams/[streamId]/components/ShareAndEmbed.tsx
- packages/app/app/studio/[organization]/livestreams/[streamId]/page.tsx
Fixes share-dialog-in-stream-page-not-showing-proper-url
The error occurred because an environment variable was passed that was never updated in Vercel. I opted to use `window.location.origin` instead of relying on the environment variable.
closes #988
> 🐛 Fix: share-dialog-in-stream-page-not-showing-proper-url

- packages/app/app/(vod)/watch/page.tsx
- packages/app/app/[organization]/watch/page.tsx
- packages/app/app/speaker/[session]/page.tsx
🐛 Fix Broken Social Share Thumbnails for sessions
The bug was caused by using Nullish Coalescing (??) operator which only considers null and undefined as `nullish` values. It will return the right-hand side only if the left-hand side is null or undefined.  
```  const thumbnail = video.coverImage || (await generateThumbnailAction(video)); ```
Replace the operator with Logical OR (||) operator which returns the first truthy value. Since `coverImages` in our sessions are set to empty string by default, the Logical OR (||) will evaluate the right-hand side instead (generateThumbnailAction)
closes #1038
> 🐛 FIx Broken Social Share Thumbnails for sessions

- packages/app/app/studio/[organization]/clips/[stageId]/ClipContext.tsx
- packages/app/app/studio/[organization]/clips/[stageId]/Timeline/PlayHead.tsx
- packages/app/app/studio/[organization]/clips/[stageId]/Timeline/TrimmControls.tsx
- packages/app/app/studio/[organization]/clips/[stageId]/Timeline/index.tsx
- packages/app/app/studio/[organization]/clips/[stageId]/topBar/CreateClipButton.tsx
Clipping page UX changes on the timeline.
- [x ] UI/UX improvement 💄
- You can now click on the timeline to move the playhead. 
- You can now drag the slider and the playhead won't follow. 
- When creating a clip, you can click on preview to play at the very start of the clip slider.
- Commented some duplicated code. 
-
[Detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]
- Rearranged some z indexes on the timeline.
- [ x] My code adheres to the coding and style guidelines of the project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made …
> 💄Playhead dragging improved and preview

- packages/app/app/studio/[organization]/clips/[stageId]/ClipContext.tsx
- packages/server/src/services/marker.service.ts
1.  Sort markers by startTime 
2. Fix null bugs when importing markers 
> ♻️ sort markers by startTime and fix minor import bug

- packages/app/components/misc/VideoCard/thumbnail.tsx
---
This pull request refactors the `Thumbnail` component (`packages/app/components/misc/VideoCard/thumbnail.tsx`) to simplify its implementation and address previous discussions regarding `next/image` properties.
The key changes include:
- **Removal of Blur Placeholder:** The `placeholder="blur"` and `blurDataURL={srcUrl}` props have been removed from the `next/image` component. The `blurDataURL` was previously misconfigured, and this change removes the blur-up placeholder effect.
- **Removal of Explicit Quality Setting:** The `quality={100}` prop has been removed. The `next/image` component will now use its default quality settings or those configured globally in `next.config.js`.
- **Removed Unused Hooks:** `useEffect` and `useState` imports and any associated logic have been removed, …
> ♻️ Refactor: Simplify Thumbnail component and remove blur placeholder
